### ISSUE TITLE
Help- color box

### ISSUE THREAD

**Issue by AyeshaIkhlas21** [AyeshaIkhlas21/web-design-2-independent-project#2]
Hi, 
How I add the color box in the middle section?

![Screen Shot 2021-11-24 at 4 19 47 PM](https://user-images.githubusercontent.com/77422853/143314382-0ecb3615-79e8-4244-920b-a55dda23acd0.png)
 
@anna-pokhilenko

**Comment by anna-pokhilenko** [comment]
One thing that I noticed is that your classes have spaces in between. So if you want a class like "event card" as one class, you need to have a dash to link the words. 
So it will be "event-card".
Because CSS allows us to have multiple classes on, and they are usually divided by space. The way you built your classes, you actually created two classes "event" and "card". 
<img width="686" alt="Screen Shot 2021-11-24 at 5 20 27 PM" src="https://user-images.githubusercontent.com/55008926/143320012-633aabcb-64d5-4759-ac07-0c1543079d9b.png">

The right way will be:
<img width="689" alt="Screen Shot 2021-11-24 at 5 20 57 PM" src="https://user-images.githubusercontent.com/55008926/143320051-85ba7866-c117-46aa-a2c9-086cc1613291.png">
 
And then you can tag the class in the CSS and apply whatever you need.

The other thing I spotted, that your main ends right after it starts. But this is not the right thing to approach main. The main should wrap around all the content on your page. 
It will be closed right before your footer.
When you will fix that, your whole page will be this dark colour.

I also 
You will have to tag the cards that you want to be white and style them in your CSS. I made screenshots of the changes I made and of the end result. Try it yourself. 

The width: 100vw; stands for "stretch the section to 100% view width".

<img width="339" alt="Screen Shot 2021-11-24 at 5 34 04 PM" src="https://user-images.githubusercontent.com/55008926/143321433-c24af1d0-15bd-4689-8b95-01d0508861d4.png">
<img width="270" alt="Screen Shot 2021-11-24 at 5 33 59 PM" src="https://user-images.githubusercontent.com/55008926/143321434-a0eaae05-6d2a-432d-aa25-b1196bddb664.png">
<img width="497" alt="Screen Shot 2021-11-24 at 5 34 30 PM" src="https://user-images.githubusercontent.com/55008926/143321432-1e401f83-b4f0-4ec1-8c58-c5b68b8d2660.png">

Hope this helps!

**Comment by AyeshaIkhlas21** [comment]
I got it. 
How do you move the left corner? I tried margin and padding. It didn't work. 
Case Study: Left corner. 
<img width="485" alt="Screen Shot 2021-11-25 at 10 38 21 PM" src="https://user-images.githubusercontent.com/77422853/143523173-54cc34ff-a375-4f93-ab18-112c7380b461.png">
![Screen Shot 2021-11-25 at 10 41 29 PM](https://user-images.githubusercontent.com/77422853/143523364-782a22b8-1705-4b8f-a2aa-656bb942a56a.png)

**Comment by anna-pokhilenko** [comment]
For this one, you can simply tag the class and say `text-align: left;`

<img width="410" alt="Screen Shot 2021-11-26 at 9 07 12 AM" src="https://user-images.githubusercontent.com/55008926/143593007-62bb1c48-2d80-438a-85ce-758de1e933bd.png">

This will fix the issue!

<img width="444" alt="Screen Shot 2021-11-26 at 9 10 26 AM" src="https://user-images.githubusercontent.com/55008926/143593383-2ce24692-fda9-4243-9a3d-3e5bf5e43dee.png">

The other thing you can tweak in your html is your h2. You have two h2 in a row. They don't look like they are equally important in your hierarchy. 
I would either change "Case Study" h2 into h3 or even state that this is a p tag. Up to you!


<img width="757" alt="Screen Shot 2021-11-26 at 9 04 12 AM" src="https://user-images.githubusercontent.com/55008926/143593288-eadf0895-4d10-4a91-894e-b4f95393f0df.png">

<img width="781" alt="Screen Shot 2021-11-26 at 9 05 56 AM" src="https://user-images.githubusercontent.com/55008926/143593287-25f84ba7-a968-4ba0-bd78-ffdc9868640f.png">
